name: package

on:
  push:
    branches:
      - master
      - develop
    tags:
      - 'v*.*'
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.7
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: python -m pip install .[test]
    - name: Test
      run: python -m unittest -v

  upload:
    if: ${{ startsWith( github.ref , 'refs/tags/' ) }}
    runs-on: ubuntu-latest
    container: python:3.7
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: python setup.py sdist
    - name: Install Twine
      run: python -m pip install twine
    - name: Upload
      run: python -m twine upload --verbose dist/*
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        TWINE_REPOSITORY: ${{ secrets.TWINE_REPOSITORY }}
        TWINE_NON_INTERACTIVE: 1
